apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: default
type: Opaque
data:
  username: YWRtaW4=  # 'admin' in base64
  password: UEAkJHcwcmQ=  # 'P@$$w0rd' in base64
  connection_string: bXlzcWw6Ly9hZG1pbjpQQCQkdzByZEBteXNxbC5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsOjMzMDYvZGI=